name: awee
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0

# dependencies:
#   flutter:
#     sdk: flutter
#   http: ^0.13.5
#   flutter_bloc: ^8.1.3
#   equatable: ^2.0.5
#   shared_preferences: ^2.5.3
#   intl: ^0.18.1
#   provider: ^6.1.2
#   dio: ^5.2.0
#   shimmer: ^3.0.0
#   lottie: ^2.3.2
#   flutter_local_notifications: ^16.3.0
#   awesome_notifications: ^0.8.0
  
  
#   cupertino_icons: ^1.0.8

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  provider: ^6.1.2
  dio: ^5.2.0
  shimmer: ^3.0.0
  lottie: ^2.3.2
  # flutter_local_notifications: ^15.1.1
  fl_chart: ^0.71.0
  animated_counter: ^1.0.0


  # awesome_notifications:
  #   git:
  #     url: https://github.com/rafaelsetragni/awesome_notifications.git
  #     ref: development

  cupertino_icons: ^1.0.8
  # flutter_localizations:
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/


 


 
